name: Reproduce Issues

on:
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: |
          npm install --ignore-scripts --global @salesforce/cli
          sf --version
          sf plugins --core
      - name: Authenticate DevHub and create scratch org with sample metadata
        env:
          SFDX_AUTH_URL_DEVHUB: ${{ secrets.SFDX_AUTH_URL_DEVHUB }}
        run: |
          echo "${SFDX_AUTH_URL_DEVHUB}" | sf org login sfdx-url --set-default-dev-hub --sfdx-url-stdin
          ./scripts/develop.sh
      - name: Reproduce Issue retrieving nested EmailTemplateFolder with source tracking
        run: ./test/retrieve-using-source-tracking.sh
      - name: Reproduce Issue deploying nested EmailTemplate using Metadata API name
        run: ./test/deploy-using-metadata-api-names.sh
      - name: Delete scratch org
        if: always()
        run: |
          sf org delete scratch -p
